name: Pages

on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node >= 20.19（建议 22）
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'   # 用 npm 缓存

      - name: Use official npm registry
        run: npm config set registry https://registry.npmjs.org

      - name: Show versions
        run: |
          node -v
          npm -v

      # 有 lockfile 用 npm ci；否则用 npm install
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
