name: Pages

on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node 22（或用 '20.19.0' 及以上）
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'              # 用 npm 缓存，替代手动缓存 node_modules

      - name: Use official npm registry
        run: npm config set registry https://registry.npmjs.org

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Clean & install
        run: |
          rm -rf node_modules package-lock.json
          npm ci || npm i

      - name: Build
        run: npm run build          # 通常等价于 hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
